
Address.create!([
  {public_place_id: 1, private_place_number: 1, private_place_type_id: 1}
])
AddressCocoon.create!([
  {line_one: "1234", line_two: "32442", zip_code: 234234, person_cocoon_id: 4},
  {line_one: "1234", line_two: "32442", zip_code: 234234, person_cocoon_id: 4},
  {line_one: "456", line_two: "345", zip_code: 234234, person_cocoon_id: 4},
  {line_one: "aaa", line_two: "aaa", zip_code: 222, person_cocoon_id: 5},
  {line_one: "bbb", line_two: "bbr", zip_code: 2324342, person_cocoon_id: 5},
  {line_one: "1", line_two: "2", zip_code: 3, person_cocoon_id: 3},
  {line_one: "3", line_two: "1", zip_code: 1, person_cocoon_id: 3},
  {line_one: "456", line_two: "345", zip_code: 234234, person_cocoon_id: 4}
])
AddressType.create!([
  {name: "Home"},
  {name: "Business"},
  {name: "Billing"},
  {name: "Shipping"}
])
assignmentType.create!([
  {name: "Collect", description: "Collect donation from a donor"},
  {name: "Store", description: "Store donations on a distribution hub"},
  {name: "Delivery", description: "Transport donations to consumer"},
  {name: "Lost", description: "Inventory the storage to assure the donations are proper to consumption"},
  {name: "Fundraise", description: "contact possible donors"}
])
ConsentFormType.create!([
  {description: "Volunteer", html_text: "By clicking 'OK' in this form you are agreeing in volunteering on supply!Foods initiative"},
  {description: "Donor", html_text: "by clicking 'ok' on this form you are agreeing in donate to the supply!food initiative"},
  {description: "Supplier", html_text: "by clicking 'ok' on this for, you are agreeing in work as supplier to the 'supply!food' initiative"}
])
Country.create!([
  {name: "Afghanistan", alpha_2_code: "AF", alpha_3_code: "AFG", numeric_code: 4, independent: true},
  {name: "Åland Islands", alpha_2_code: "AX", alpha_3_code: "ALA", numeric_code: 248, independent: false},
  {name: "Albania", alpha_2_code: "AL", alpha_3_code: "ALB", numeric_code: 8, independent: true},
  {name: "Algeria", alpha_2_code: "DZ", alpha_3_code: "DZA", numeric_code: 12, independent: true},
  {name: "American Samoa", alpha_2_code: "AS", alpha_3_code: "ASM", numeric_code: 16, independent: false},
  {name: "Andorra", alpha_2_code: "AD", alpha_3_code: "AND", numeric_code: 20, independent: true},
  {name: "Angola", alpha_2_code: "AO", alpha_3_code: "AGO", numeric_code: 24, independent: true},
  {name: "Anguilla", alpha_2_code: "AI", alpha_3_code: "AIA", numeric_code: 660, independent: false},
  {name: "Antarctica", alpha_2_code: "AQ", alpha_3_code: "ATA", numeric_code: 10, independent: false},
  {name: "Antigua and Barbuda", alpha_2_code: "AG", alpha_3_code: "ATG", numeric_code: 28, independent: true},
  {name: "Argentina", alpha_2_code: "AR", alpha_3_code: "ARG", numeric_code: 32, independent: true},
  {name: "Armenia", alpha_2_code: "AM", alpha_3_code: "ARM", numeric_code: 51, independent: true},
  {name: "Aruba", alpha_2_code: "AW", alpha_3_code: "ABW", numeric_code: 533, independent: false},
  {name: "Australia", alpha_2_code: "AU", alpha_3_code: "AUS", numeric_code: 36, independent: true},
  {name: "Austria", alpha_2_code: "AT", alpha_3_code: "AUT", numeric_code: 40, independent: true},
  {name: "Azerbaijan", alpha_2_code: "AZ", alpha_3_code: "AZE", numeric_code: 31, independent: true},
  {name: "Bahamas", alpha_2_code: "BS", alpha_3_code: "BHS", numeric_code: 44, independent: true},
  {name: "Bahrain", alpha_2_code: "BH", alpha_3_code: "BHR", numeric_code: 48, independent: true},
  {name: "Bangladesh", alpha_2_code: "BD", alpha_3_code: "BGD", numeric_code: 50, independent: true},
  {name: "Barbados", alpha_2_code: "BB", alpha_3_code: "BRB", numeric_code: 52, independent: true},
  {name: "Belarus", alpha_2_code: "BY", alpha_3_code: "BLR", numeric_code: 112, independent: true},
  {name: "Belgium", alpha_2_code: "BE", alpha_3_code: "BEL", numeric_code: 56, independent: true},
  {name: "Belize", alpha_2_code: "BZ", alpha_3_code: "BLZ", numeric_code: 84, independent: true},
  {name: "Benin", alpha_2_code: "BJ", alpha_3_code: "BEN", numeric_code: 204, independent: true},
  {name: "Bermuda", alpha_2_code: "BM", alpha_3_code: "BMU", numeric_code: 60, independent: false},
  {name: "Bhutan", alpha_2_code: "BT", alpha_3_code: "BTN", numeric_code: 64, independent: true},
  {name: "Bolivia (Plurinational State of)", alpha_2_code: "BO", alpha_3_code: "BOL", numeric_code: 68, independent: true},
  {name: "Bonaire, Sint Eustatius and Saba", alpha_2_code: "BQ", alpha_3_code: "BES", numeric_code: 535, independent: false},
  {name: "Bosnia and Herzegovina", alpha_2_code: "BA", alpha_3_code: "BIH", numeric_code: 70, independent: true},
  {name: "Botswana", alpha_2_code: "BW", alpha_3_code: "BWA", numeric_code: 72, independent: true},
  {name: "Bouvet Island", alpha_2_code: "BV", alpha_3_code: "BVT", numeric_code: 74, independent: false},
  {name: "Brazil", alpha_2_code: "BR", alpha_3_code: "BRA", numeric_code: 76, independent: true},
  {name: "British Indian Ocean Territory", alpha_2_code: "IO", alpha_3_code: "IOT", numeric_code: 86, independent: false},
  {name: "Brunei Darussalam", alpha_2_code: "BN", alpha_3_code: "BRN", numeric_code: 96, independent: true},
  {name: "Bulgaria", alpha_2_code: "BG", alpha_3_code: "BGR", numeric_code: 100, independent: true},
  {name: "Burkina Faso", alpha_2_code: "BF", alpha_3_code: "BFA", numeric_code: 854, independent: true},
  {name: "Burundi", alpha_2_code: "BI", alpha_3_code: "BDI", numeric_code: 108, independent: true},
  {name: "Cabo Verde", alpha_2_code: "CV", alpha_3_code: "CPV", numeric_code: 132, independent: true},
  {name: "Cambodia", alpha_2_code: "KH", alpha_3_code: "KHM", numeric_code: 116, independent: true},
  {name: "Cameroon", alpha_2_code: "CM", alpha_3_code: "CMR", numeric_code: 120, independent: true},
  {name: "Canada", alpha_2_code: "CA", alpha_3_code: "CAN", numeric_code: 124, independent: true},
  {name: "Cayman Islands", alpha_2_code: "KY", alpha_3_code: "CYM", numeric_code: 136, independent: false},
  {name: "Central African Republic", alpha_2_code: "CF", alpha_3_code: "CAF", numeric_code: 140, independent: true},
  {name: "Chad", alpha_2_code: "TD", alpha_3_code: "TCD", numeric_code: 148, independent: true},
  {name: "Chile", alpha_2_code: "CL", alpha_3_code: "CHL", numeric_code: 152, independent: true},
  {name: "China", alpha_2_code: "CN", alpha_3_code: "CHN", numeric_code: 156, independent: true},
  {name: "Christmas Island", alpha_2_code: "CX", alpha_3_code: "CXR", numeric_code: 162, independent: false},
  {name: "Cocos (Keeling) Islands", alpha_2_code: "CC", alpha_3_code: "CCK", numeric_code: 166, independent: false},
  {name: "Colombia", alpha_2_code: "CO", alpha_3_code: "COL", numeric_code: 170, independent: true},
  {name: "Comoros", alpha_2_code: "KM", alpha_3_code: "COM", numeric_code: 174, independent: true},
  {name: "Congo", alpha_2_code: "CG", alpha_3_code: "COG", numeric_code: 178, independent: true},
  {name: "Congo (Democratic Republic of the)", alpha_2_code: "CD", alpha_3_code: "COD", numeric_code: 180, independent: true},
  {name: "Cook Islands", alpha_2_code: "CK", alpha_3_code: "COK", numeric_code: 184, independent: false},
  {name: "Costa Rica", alpha_2_code: "CR", alpha_3_code: "CRI", numeric_code: 188, independent: true},
  {name: "Côte d'Ivoire", alpha_2_code: "CI", alpha_3_code: "CIV", numeric_code: 384, independent: true},
  {name: "Croatia", alpha_2_code: "HR", alpha_3_code: "HRV", numeric_code: 191, independent: true},
  {name: "Cuba", alpha_2_code: "CU", alpha_3_code: "CUB", numeric_code: 192, independent: true},
  {name: "Curaçao", alpha_2_code: "CW", alpha_3_code: "CUW", numeric_code: 531, independent: false},
  {name: "Cyprus", alpha_2_code: "CY", alpha_3_code: "CYP", numeric_code: 196, independent: true},
  {name: "Czechia", alpha_2_code: "CZ", alpha_3_code: "CZE", numeric_code: 203, independent: true},
  {name: "Denmark", alpha_2_code: "DK", alpha_3_code: "DNK", numeric_code: 208, independent: true},
  {name: "Djibouti", alpha_2_code: "DJ", alpha_3_code: "DJI", numeric_code: 262, independent: true},
  {name: "Dominica", alpha_2_code: "DM", alpha_3_code: "DMA", numeric_code: 212, independent: true},
  {name: "Dominican Republic", alpha_2_code: "DO", alpha_3_code: "DOM", numeric_code: 214, independent: true},
  {name: "Ecuador", alpha_2_code: "EC", alpha_3_code: "ECU", numeric_code: 218, independent: true},
  {name: "Egypt", alpha_2_code: "EG", alpha_3_code: "EGY", numeric_code: 818, independent: true},
  {name: "El Salvador", alpha_2_code: "SV", alpha_3_code: "SLV", numeric_code: 222, independent: true},
  {name: "Equatorial Guinea", alpha_2_code: "GQ", alpha_3_code: "GNQ", numeric_code: 226, independent: true},
  {name: "Eritrea", alpha_2_code: "ER", alpha_3_code: "ERI", numeric_code: 232, independent: true},
  {name: "Estonia", alpha_2_code: "EE", alpha_3_code: "EST", numeric_code: 233, independent: true},
  {name: "Ethiopia", alpha_2_code: "ET", alpha_3_code: "ETH", numeric_code: 231, independent: true},
  {name: "Falkland Islands (Malvinas)", alpha_2_code: "FK", alpha_3_code: "FLK", numeric_code: 238, independent: false},
  {name: "Faroe Islands", alpha_2_code: "FO", alpha_3_code: "FRO", numeric_code: 234, independent: false},
  {name: "Fiji", alpha_2_code: "FJ", alpha_3_code: "FJI", numeric_code: 242, independent: true},
  {name: "Finland", alpha_2_code: "FI", alpha_3_code: "FIN", numeric_code: 246, independent: true},
  {name: "France", alpha_2_code: "FR", alpha_3_code: "FRA", numeric_code: 250, independent: true},
  {name: "French Guiana", alpha_2_code: "GF", alpha_3_code: "GUF", numeric_code: 254, independent: false},
  {name: "French Polynesia", alpha_2_code: "PF", alpha_3_code: "PYF", numeric_code: 258, independent: false},
  {name: "French Southern Territories", alpha_2_code: "TF", alpha_3_code: "ATF", numeric_code: 260, independent: false},
  {name: "Gabon", alpha_2_code: "GA", alpha_3_code: "GAB", numeric_code: 266, independent: true},
  {name: "Gambia", alpha_2_code: "GM", alpha_3_code: "GMB", numeric_code: 270, independent: true},
  {name: "Georgia", alpha_2_code: "GE", alpha_3_code: "GEO", numeric_code: 268, independent: true},
  {name: "Germany", alpha_2_code: "DE", alpha_3_code: "DEU", numeric_code: 276, independent: true},
  {name: "Ghana", alpha_2_code: "GH", alpha_3_code: "GHA", numeric_code: 288, independent: true},
  {name: "Gibraltar", alpha_2_code: "GI", alpha_3_code: "GIB", numeric_code: 292, independent: false},
  {name: "Greece", alpha_2_code: "GR", alpha_3_code: "GRC", numeric_code: 300, independent: true},
  {name: "Greenland", alpha_2_code: "GL", alpha_3_code: "GRL", numeric_code: 304, independent: false},
  {name: "Grenada", alpha_2_code: "GD", alpha_3_code: "GRD", numeric_code: 308, independent: true},
  {name: "Guadeloupe", alpha_2_code: "GP", alpha_3_code: "GLP", numeric_code: 312, independent: false},
  {name: "Guam", alpha_2_code: "GU", alpha_3_code: "GUM", numeric_code: 316, independent: false},
  {name: "Guatemala", alpha_2_code: "GT", alpha_3_code: "GTM", numeric_code: 320, independent: true},
  {name: "Guernsey", alpha_2_code: "GG", alpha_3_code: "GGY", numeric_code: 831, independent: false},
  {name: "Guinea", alpha_2_code: "GN", alpha_3_code: "GIN", numeric_code: 324, independent: true},
  {name: "Guinea-Bissau", alpha_2_code: "GW", alpha_3_code: "GNB", numeric_code: 624, independent: true},
  {name: "Guyana", alpha_2_code: "GY", alpha_3_code: "GUY", numeric_code: 328, independent: true},
  {name: "Haiti", alpha_2_code: "HT", alpha_3_code: "HTI", numeric_code: 332, independent: true},
  {name: "Heard Island and McDonald Islands", alpha_2_code: "HM", alpha_3_code: "HMD", numeric_code: 334, independent: false},
  {name: "Holy See", alpha_2_code: "VA", alpha_3_code: "VAT", numeric_code: 336, independent: true},
  {name: "Honduras", alpha_2_code: "HN", alpha_3_code: "HND", numeric_code: 340, independent: true},
  {name: "Hong Kong", alpha_2_code: "HK", alpha_3_code: "HKG", numeric_code: 344, independent: false},
  {name: "Hungary", alpha_2_code: "HU", alpha_3_code: "HUN", numeric_code: 348, independent: true},
  {name: "Iceland", alpha_2_code: "IS", alpha_3_code: "ISL", numeric_code: 352, independent: true},
  {name: "India", alpha_2_code: "IN", alpha_3_code: "IND", numeric_code: 356, independent: true},
  {name: "Indonesia", alpha_2_code: "ID", alpha_3_code: "IDN", numeric_code: 360, independent: true},
  {name: "Iran (Islamic Republic of)", alpha_2_code: "IR", alpha_3_code: "IRN", numeric_code: 364, independent: true},
  {name: "Iraq", alpha_2_code: "IQ", alpha_3_code: "IRQ", numeric_code: 368, independent: true},
  {name: "Ireland", alpha_2_code: "IE", alpha_3_code: "IRL", numeric_code: 372, independent: true},
  {name: "Isle of Man", alpha_2_code: "IM", alpha_3_code: "IMN", numeric_code: 833, independent: false},
  {name: "Israel", alpha_2_code: "IL", alpha_3_code: "ISR", numeric_code: 376, independent: true},
  {name: "Italy", alpha_2_code: "IT", alpha_3_code: "ITA", numeric_code: 380, independent: true},
  {name: "Jamaica", alpha_2_code: "JM", alpha_3_code: "JAM", numeric_code: 388, independent: true},
  {name: "Japan", alpha_2_code: "JP", alpha_3_code: "JPN", numeric_code: 392, independent: true},
  {name: "Jersey", alpha_2_code: "JE", alpha_3_code: "JEY", numeric_code: 832, independent: false},
  {name: "Jordan", alpha_2_code: "JO", alpha_3_code: "JOR", numeric_code: 400, independent: true},
  {name: "Kazakhstan", alpha_2_code: "KZ", alpha_3_code: "KAZ", numeric_code: 398, independent: true},
  {name: "Kenya", alpha_2_code: "KE", alpha_3_code: "KEN", numeric_code: 404, independent: true},
  {name: "Kiribati", alpha_2_code: "KI", alpha_3_code: "KIR", numeric_code: 296, independent: true},
  {name: "Korea (Democratic People's Republic of)", alpha_2_code: "KP", alpha_3_code: "PRK", numeric_code: 408, independent: true},
  {name: "Korea (Republic of)", alpha_2_code: "KR", alpha_3_code: "KOR", numeric_code: 410, independent: true},
  {name: "Kuwait", alpha_2_code: "KW", alpha_3_code: "KWT", numeric_code: 414, independent: true},
  {name: "Kyrgyzstan", alpha_2_code: "KG", alpha_3_code: "KGZ", numeric_code: 417, independent: true},
  {name: "Lao People's Democratic Republic", alpha_2_code: "LA", alpha_3_code: "LAO", numeric_code: 418, independent: true},
  {name: "Latvia", alpha_2_code: "LV", alpha_3_code: "LVA", numeric_code: 428, independent: true},
  {name: "Lebafalsen", alpha_2_code: "LB", alpha_3_code: "LBN", numeric_code: 422, independent: true},
  {name: "Lesotho", alpha_2_code: "LS", alpha_3_code: "LSO", numeric_code: 426, independent: true},
  {name: "Liberia", alpha_2_code: "LR", alpha_3_code: "LBR", numeric_code: 430, independent: true},
  {name: "Libya", alpha_2_code: "LY", alpha_3_code: "LBY", numeric_code: 434, independent: true},
  {name: "Liechtenstein", alpha_2_code: "LI", alpha_3_code: "LIE", numeric_code: 438, independent: true},
  {name: "Lithuania", alpha_2_code: "LT", alpha_3_code: "LTU", numeric_code: 440, independent: true},
  {name: "Luxembourg", alpha_2_code: "LU", alpha_3_code: "LUX", numeric_code: 442, independent: true},
  {name: "Macao", alpha_2_code: "MO", alpha_3_code: "MAC", numeric_code: 446, independent: false},
  {name: "Macedonia (the former Yugoslav Republic of)", alpha_2_code: "MK", alpha_3_code: "MKD", numeric_code: 807, independent: true},
  {name: "Madagascar", alpha_2_code: "MG", alpha_3_code: "MDG", numeric_code: 450, independent: true},
  {name: "Malawi", alpha_2_code: "MW", alpha_3_code: "MWI", numeric_code: 454, independent: true},
  {name: "Malaysia", alpha_2_code: "MY", alpha_3_code: "MYS", numeric_code: 458, independent: true},
  {name: "Maldives", alpha_2_code: "MV", alpha_3_code: "MDV", numeric_code: 462, independent: true},
  {name: "Mali", alpha_2_code: "ML", alpha_3_code: "MLI", numeric_code: 466, independent: true},
  {name: "Malta", alpha_2_code: "MT", alpha_3_code: "MLT", numeric_code: 470, independent: true},
  {name: "Marshall Islands", alpha_2_code: "MH", alpha_3_code: "MHL", numeric_code: 584, independent: true},
  {name: "Martinique", alpha_2_code: "MQ", alpha_3_code: "MTQ", numeric_code: 474, independent: false},
  {name: "Mauritania", alpha_2_code: "MR", alpha_3_code: "MRT", numeric_code: 478, independent: true},
  {name: "Mauritius", alpha_2_code: "MU", alpha_3_code: "MUS", numeric_code: 480, independent: true},
  {name: "Mayotte", alpha_2_code: "YT", alpha_3_code: "MYT", numeric_code: 175, independent: false},
  {name: "Mexico", alpha_2_code: "MX", alpha_3_code: "MEX", numeric_code: 484, independent: true},
  {name: "Micronesia (Federated States of)", alpha_2_code: "FM", alpha_3_code: "FSM", numeric_code: 583, independent: true},
  {name: "Moldova (Republic of)", alpha_2_code: "MD", alpha_3_code: "MDA", numeric_code: 498, independent: true},
  {name: "Monaco", alpha_2_code: "MC", alpha_3_code: "MCO", numeric_code: 492, independent: true},
  {name: "Mongolia", alpha_2_code: "MN", alpha_3_code: "MNG", numeric_code: 496, independent: true},
  {name: "Montenegro", alpha_2_code: "ME", alpha_3_code: "MNE", numeric_code: 499, independent: true},
  {name: "Montserrat", alpha_2_code: "MS", alpha_3_code: "MSR", numeric_code: 500, independent: false},
  {name: "Morocco", alpha_2_code: "MA", alpha_3_code: "MAR", numeric_code: 504, independent: true},
  {name: "Mozambique", alpha_2_code: "MZ", alpha_3_code: "MOZ", numeric_code: 508, independent: true},
  {name: "Myanmar", alpha_2_code: "MM", alpha_3_code: "MMR", numeric_code: 104, independent: true},
  {name: "Namibia", alpha_2_code: "NA", alpha_3_code: "NAM", numeric_code: 516, independent: true},
  {name: "Nauru", alpha_2_code: "NR", alpha_3_code: "NRU", numeric_code: 520, independent: true},
  {name: "Nepal", alpha_2_code: "NP", alpha_3_code: "NPL", numeric_code: 524, independent: true},
  {name: "Netherlands", alpha_2_code: "NL", alpha_3_code: "NLD", numeric_code: 528, independent: true},
  {name: "New Caledonia", alpha_2_code: "NC", alpha_3_code: "NCL", numeric_code: 540, independent: false},
  {name: "New Zealand", alpha_2_code: "NZ", alpha_3_code: "NZL", numeric_code: 554, independent: true},
  {name: "Nicaragua", alpha_2_code: "NI", alpha_3_code: "NIC", numeric_code: 558, independent: true},
  {name: "Niger", alpha_2_code: "NE", alpha_3_code: "NER", numeric_code: 562, independent: true},
  {name: "Nigeria", alpha_2_code: "NG", alpha_3_code: "NGA", numeric_code: 566, independent: true},
  {name: "Niue", alpha_2_code: "NU", alpha_3_code: "NIU", numeric_code: 570, independent: false},
  {name: "falserfolk Island", alpha_2_code: "NF", alpha_3_code: "NFK", numeric_code: 574, independent: false},
  {name: "falserthern Mariana Islands", alpha_2_code: "MP", alpha_3_code: "MNP", numeric_code: 580, independent: false},
  {name: "falserway", alpha_2_code: "false", alpha_3_code: "falseR", numeric_code: 578, independent: true},
  {name: "Oman", alpha_2_code: "OM", alpha_3_code: "OMN", numeric_code: 512, independent: true},
  {name: "Pakistan", alpha_2_code: "PK", alpha_3_code: "PAK", numeric_code: 586, independent: true},
  {name: "Palau", alpha_2_code: "PW", alpha_3_code: "PLW", numeric_code: 585, independent: true},
  {name: "Palestine, State of", alpha_2_code: "PS", alpha_3_code: "PSE", numeric_code: 275, independent: false},
  {name: "Panama", alpha_2_code: "PA", alpha_3_code: "PAN", numeric_code: 591, independent: true},
  {name: "Papua New Guinea", alpha_2_code: "PG", alpha_3_code: "PNG", numeric_code: 598, independent: true},
  {name: "Paraguay", alpha_2_code: "PY", alpha_3_code: "PRY", numeric_code: 600, independent: true},
  {name: "Peru", alpha_2_code: "PE", alpha_3_code: "PER", numeric_code: 604, independent: true},
  {name: "Philippines", alpha_2_code: "PH", alpha_3_code: "PHL", numeric_code: 608, independent: true},
  {name: "Pitcairn", alpha_2_code: "PN", alpha_3_code: "PCN", numeric_code: 612, independent: false},
  {name: "Poland", alpha_2_code: "PL", alpha_3_code: "POL", numeric_code: 616, independent: true},
  {name: "Portugal", alpha_2_code: "PT", alpha_3_code: "PRT", numeric_code: 620, independent: true},
  {name: "Puerto Rico", alpha_2_code: "PR", alpha_3_code: "PRI", numeric_code: 630, independent: false},
  {name: "Qatar", alpha_2_code: "QA", alpha_3_code: "QAT", numeric_code: 634, independent: true},
  {name: "Réunion", alpha_2_code: "RE", alpha_3_code: "REU", numeric_code: 638, independent: false},
  {name: "Romania", alpha_2_code: "RO", alpha_3_code: "ROU", numeric_code: 642, independent: true},
  {name: "Russian Federation", alpha_2_code: "RU", alpha_3_code: "RUS", numeric_code: 643, independent: true},
  {name: "Rwanda", alpha_2_code: "RW", alpha_3_code: "RWA", numeric_code: 646, independent: true},
  {name: "Saint Barthélemy", alpha_2_code: "BL", alpha_3_code: "BLM", numeric_code: 652, independent: false},
  {name: "Saint Helena, Ascension and Tristan da Cunha", alpha_2_code: "SH", alpha_3_code: "SHN", numeric_code: 654, independent: false},
  {name: "Saint Kitts and Nevis", alpha_2_code: "KN", alpha_3_code: "KNA", numeric_code: 659, independent: true},
  {name: "Saint Lucia", alpha_2_code: "LC", alpha_3_code: "LCA", numeric_code: 662, independent: true},
  {name: "Saint Martin (French part)", alpha_2_code: "MF", alpha_3_code: "MAF", numeric_code: 663, independent: false},
  {name: "Saint Pierre and Miquelon", alpha_2_code: "PM", alpha_3_code: "SPM", numeric_code: 666, independent: false},
  {name: "Saint Vincent and the Grenadines", alpha_2_code: "VC", alpha_3_code: "VCT", numeric_code: 670, independent: true},
  {name: "Samoa", alpha_2_code: "WS", alpha_3_code: "WSM", numeric_code: 882, independent: true},
  {name: "San Marifalse", alpha_2_code: "SM", alpha_3_code: "SMR", numeric_code: 674, independent: true},
  {name: "Sao Tome and Principe", alpha_2_code: "ST", alpha_3_code: "STP", numeric_code: 678, independent: true},
  {name: "Saudi Arabia", alpha_2_code: "SA", alpha_3_code: "SAU", numeric_code: 682, independent: true},
  {name: "Senegal", alpha_2_code: "SN", alpha_3_code: "SEN", numeric_code: 686, independent: true},
  {name: "Serbia", alpha_2_code: "RS", alpha_3_code: "SRB", numeric_code: 688, independent: true},
  {name: "Seychelles", alpha_2_code: "SC", alpha_3_code: "SYC", numeric_code: 690, independent: true},
  {name: "Sierra Leone", alpha_2_code: "SL", alpha_3_code: "SLE", numeric_code: 694, independent: true},
  {name: "Singapore", alpha_2_code: "SG", alpha_3_code: "SGP", numeric_code: 702, independent: true},
  {name: "Sint Maarten (Dutch part)", alpha_2_code: "SX", alpha_3_code: "SXM", numeric_code: 534, independent: false},
  {name: "Slovakia", alpha_2_code: "SK", alpha_3_code: "SVK", numeric_code: 703, independent: true},
  {name: "Slovenia", alpha_2_code: "SI", alpha_3_code: "SVN", numeric_code: 705, independent: true},
  {name: "Solomon Islands", alpha_2_code: "SB", alpha_3_code: "SLB", numeric_code: 90, independent: true},
  {name: "Somalia", alpha_2_code: "SO", alpha_3_code: "SOM", numeric_code: 706, independent: true},
  {name: "South Africa", alpha_2_code: "ZA", alpha_3_code: "ZAF", numeric_code: 710, independent: true},
  {name: "South Georgia and the South Sandwich Islands", alpha_2_code: "GS", alpha_3_code: "SGS", numeric_code: 239, independent: false},
  {name: "South Sudan", alpha_2_code: "SS", alpha_3_code: "SSD", numeric_code: 728, independent: true},
  {name: "Spain", alpha_2_code: "ES", alpha_3_code: "ESP", numeric_code: 724, independent: true},
  {name: "Sri Lanka", alpha_2_code: "LK", alpha_3_code: "LKA", numeric_code: 144, independent: true},
  {name: "Sudan", alpha_2_code: "SD", alpha_3_code: "SDN", numeric_code: 729, independent: true},
  {name: "Suriname", alpha_2_code: "SR", alpha_3_code: "SUR", numeric_code: 740, independent: true},
  {name: "Svalbard and Jan Mayen", alpha_2_code: "SJ", alpha_3_code: "SJM", numeric_code: 744, independent: false},
  {name: "Swaziland", alpha_2_code: "SZ", alpha_3_code: "SWZ", numeric_code: 748, independent: true},
  {name: "Sweden", alpha_2_code: "SE", alpha_3_code: "SWE", numeric_code: 752, independent: true},
  {name: "Switzerland", alpha_2_code: "CH", alpha_3_code: "CHE", numeric_code: 756, independent: true},
  {name: "Syrian Arab Republic", alpha_2_code: "SY", alpha_3_code: "SYR", numeric_code: 760, independent: true},
  {name: "Taiwan, Province of China[a]", alpha_2_code: "TW", alpha_3_code: "TWN", numeric_code: 158, independent: false},
  {name: "Tajikistan", alpha_2_code: "TJ", alpha_3_code: "TJK", numeric_code: 762, independent: true},
  {name: "Tanzania, United Republic of", alpha_2_code: "TZ", alpha_3_code: "TZA", numeric_code: 834, independent: true},
  {name: "Thailand", alpha_2_code: "TH", alpha_3_code: "THA", numeric_code: 764, independent: true},
  {name: "Timor-Leste", alpha_2_code: "TL", alpha_3_code: "TLS", numeric_code: 626, independent: true},
  {name: "Togo", alpha_2_code: "TG", alpha_3_code: "TGO", numeric_code: 768, independent: true},
  {name: "Tokelau", alpha_2_code: "TK", alpha_3_code: "TKL", numeric_code: 772, independent: false},
  {name: "Tonga", alpha_2_code: "TO", alpha_3_code: "TON", numeric_code: 776, independent: true},
  {name: "Trinidad and Tobago", alpha_2_code: "TT", alpha_3_code: "TTO", numeric_code: 780, independent: true},
  {name: "Tunisia", alpha_2_code: "TN", alpha_3_code: "TUN", numeric_code: 788, independent: true},
  {name: "Turkey", alpha_2_code: "TR", alpha_3_code: "TUR", numeric_code: 792, independent: true},
  {name: "Turkmenistan", alpha_2_code: "TM", alpha_3_code: "TKM", numeric_code: 795, independent: true},
  {name: "Turks and Caicos Islands", alpha_2_code: "TC", alpha_3_code: "TCA", numeric_code: 796, independent: false},
  {name: "Tuvalu", alpha_2_code: "TV", alpha_3_code: "TUV", numeric_code: 798, independent: true},
  {name: "Uganda", alpha_2_code: "UG", alpha_3_code: "UGA", numeric_code: 800, independent: true},
  {name: "Ukraine", alpha_2_code: "UA", alpha_3_code: "UKR", numeric_code: 804, independent: true},
  {name: "United Arab Emirates", alpha_2_code: "AE", alpha_3_code: "ARE", numeric_code: 784, independent: true},
  {name: "United Kingdom of Great Britain and falserthern Ireland", alpha_2_code: "GB", alpha_3_code: "GBR", numeric_code: 826, independent: true},
  {name: "United States of America", alpha_2_code: "US", alpha_3_code: "USA", numeric_code: 840, independent: true},
  {name: "United States Mifalser Outlying Islands", alpha_2_code: "UM", alpha_3_code: "UMI", numeric_code: 581, independent: false},
  {name: "Uruguay", alpha_2_code: "UY", alpha_3_code: "URY", numeric_code: 858, independent: true},
  {name: "Uzbekistan", alpha_2_code: "UZ", alpha_3_code: "UZB", numeric_code: 860, independent: true},
  {name: "Vanuatu", alpha_2_code: "VU", alpha_3_code: "VUT", numeric_code: 548, independent: true},
  {name: "Venezuela (Bolivarian Republic of)", alpha_2_code: "VE", alpha_3_code: "VEN", numeric_code: 862, independent: true},
  {name: "Viet Nam", alpha_2_code: "VN", alpha_3_code: "VNM", numeric_code: 704, independent: true},
  {name: "Virgin Islands (British)", alpha_2_code: "VG", alpha_3_code: "VGB", numeric_code: 92, independent: false},
  {name: "Virgin Islands (U.S.)", alpha_2_code: "VI", alpha_3_code: "VIR", numeric_code: 850, independent: false},
  {name: "Wallis and Futuna", alpha_2_code: "WF", alpha_3_code: "WLF", numeric_code: 876, independent: false},
  {name: "Western Sahara", alpha_2_code: "EH", alpha_3_code: "ESH", numeric_code: 732, independent: false},
  {name: "Yemen", alpha_2_code: "YE", alpha_3_code: "YEM", numeric_code: 887, independent: true},
  {name: "Zambia", alpha_2_code: "ZM", alpha_3_code: "ZMB", numeric_code: 894, independent: true},
  {name: "Zimbabwe", alpha_2_code: "ZW", alpha_3_code: "ZWE", numeric_code: 716, independent: true}
])
FormContact.create!([
  {name: "daniel ribeiro", subject: "problems", message: "annoying problem"},
  {name: "", subject: "", message: ""},
  {name: "daniel ribeiro", subject: "another problem", message: "this is another problem"},
  {name: "daniel ribeiro", subject: "teste 2", message: "mais um teste"}
])
GoodType.create!([
  {name: "human food", good_type_id: nil},
  {name: "canned food", good_type_id: 1},
  {name: "dairy", good_type_id: 1},
  {name: "fruits and vegetables", good_type_id: 1},
  {name: "fresh meat", good_type_id: 1},
  {name: "grains", good_type_id: 1},
  {name: "take away food", good_type_id: 1},
  {name: "beef", good_type_id: 5},
  {name: "chicken", good_type_id: 5},
  {name: "fish", good_type_id: 5},
  {name: "turkey", good_type_id: 5},
  {name: "pork", good_type_id: 5}
])
IcType.create!([
  {name: "National ID Card"},
  {name: "Social Security Number"},
  {name: "Passport"},
  {name: "Driver's license"}
])
Level.create!([
  {name: "Good samaritan", observation: "Some person who wants to help the other no matter what (11-50 meals/month)"},
  {name: "Caregiver", observation: "Just a person with a good heart (1-10 meals/month)"},
  {name: "Patron", observation: "A beacon to a better world (51+ meals/month)"}
])
MeasureUnit.create!([
  {name: "Kilogram"},
  {name: "Gram"},
  {name: "Pound"},
  {name: "Ounce"},
  {name: "Liter"},
  {name: "Mililiter"},
  {name: "Unit"}
])
Person.create!([
  {name: "João Pedro da silva", ic: "9856", person_type_id: 1, ic_type_id: 3, email: nil},
  {name: "Daniel Barbosa de Freitas Ribeiro", ic: "01234589", person_type_id: 1, ic_type_id: 1, email: nil},
  {name: "Napoleão Pereira da Silva Fraga de Melo Neto", ic: "9865667", person_type_id: 2, ic_type_id: 2, email: nil},
  {name: "", ic: "", person_type_id: 1, ic_type_id: 2, email: nil},
  {name: "", ic: "", person_type_id: 1, ic_type_id: 2, email: nil},
  {name: "fulano de tal", ic: "teste", person_type_id: 2, ic_type_id: 2, email: nil},
  {name: nil, ic: nil, person_type_id: nil, ic_type_id: nil, email: "lordofshade@hotmail.com"}
])
PersonCocoon.create!([
  {name: "teste", ic: "123123", ic_type_id: 1},
  {name: "teste", ic: "teste", ic_type_id: 2},
  {name: "ddd", ic: "111", ic_type_id: 1}
])
PersonType.create!([
  {name: "individual"},
  {name: "company"}
])
PostalCodeHint.create!([
  {code: "22270010", hint: "61", public_place_name: "Voluntários da Pátria"},
  {code: "22281035", hint: "65", public_place_name: "Voluntários da Pátria"},
  {code: "22270010", hint: "82", public_place_name: "Voluntários da Pátria"},
  {code: "22281035", hint: "73", public_place_name: "Voluntários da Pátria"}
])
PrivatePlaceType.create!([
  {name: "apartment"},
  {name: "house"},
  {name: "room"}
])
PublicPlace.create!([
  {name: "Real Grandeza", public_place_type_id: 1, postal_code_hint_id: 1, number: 199},
  {name: "Voluntários da Pátria", public_place_type_id: 1, postal_code_hint_id: 2, number: 61}
])
PublicPlaceType.create!([
  {name: "Street"},
  {name: "Avenue"},
  {name: "Road"}
])
Rank.create!([
  {name: "collector"},
  {name: "deliverer"},
  {name: "checker"},
  {name: "inventory"},
  {name: "public relations"},
  {name: "transporter"}
])
State.create!([
  {name: "Maryland", alpha_2_code: "MD", country_id: 243},
  {name: "Massachusetts", alpha_2_code: "MA", country_id: 243},
  {name: "Michigan", alpha_2_code: "MI", country_id: 243},
  {name: "Minnesota", alpha_2_code: "MN", country_id: 243},
  {name: "Mississippi", alpha_2_code: "MS", country_id: 243},
  {name: "Missouri", alpha_2_code: "MO", country_id: 243},
  {name: "Montana", alpha_2_code: "MT", country_id: 243},
  {name: "Nebraska", alpha_2_code: "NE", country_id: 243},
  {name: "Nevada", alpha_2_code: "NV", country_id: 243},
  {name: "New Hampshire", alpha_2_code: "NH", country_id: 243},
  {name: "New Jersey", alpha_2_code: "NJ", country_id: 243},
  {name: "New Mexico", alpha_2_code: "NM", country_id: 243},
  {name: "New York", alpha_2_code: "NY", country_id: 243},
  {name: "North Carolina", alpha_2_code: "NC", country_id: 243},
  {name: " North Dakota", alpha_2_code: "ND", country_id: 243},
  {name: "Ohio", alpha_2_code: "OH", country_id: 243},
  {name: "Oklahoma", alpha_2_code: "OK", country_id: 243},
  {name: "Oregon", alpha_2_code: "OR", country_id: 243},
  {name: "Pennsylvania", alpha_2_code: "PA", country_id: 243},
  {name: "Rhode Island", alpha_2_code: "RI", country_id: 243},
  {name: "South Carolina", alpha_2_code: "SC", country_id: 243},
  {name: "South Dakota", alpha_2_code: "SD", country_id: 243},
  {name: "Tennessee", alpha_2_code: "TN", country_id: 243},
  {name: "Texas", alpha_2_code: "TX", country_id: 243},
  {name: "Utah", alpha_2_code: "UT", country_id: 243},
  {name: "Vermont", alpha_2_code: "VT", country_id: 243},
  {name: "Virginia", alpha_2_code: "VA", country_id: 243},
  {name: "Washington", alpha_2_code: "WA", country_id: 243},
  {name: "West Virginia", alpha_2_code: "WV", country_id: 243},
  {name: "Wisconsin", alpha_2_code: "WI", country_id: 243},
  {name: "Wyoming", alpha_2_code: "WY", country_id: 243},
  {name: "Alabama", alpha_2_code: "AL", country_id: 243},
  {name: "Alaska", alpha_2_code: "AK", country_id: 243},
  {name: "Arizona", alpha_2_code: "AZ", country_id: 243},
  {name: "Arkansas", alpha_2_code: "AR", country_id: 243},
  {name: "California", alpha_2_code: "CA", country_id: 243},
  {name: "Colorado", alpha_2_code: "CO", country_id: 243},
  {name: "Connecticut", alpha_2_code: "CT", country_id: 243},
  {name: "Delaware", alpha_2_code: "DE", country_id: 243},
  {name: "Florida", alpha_2_code: "FL", country_id: 243},
  {name: "Georgia", alpha_2_code: "GA", country_id: 243},
  {name: "Hawaii", alpha_2_code: "HI", country_id: 243},
  {name: "Idaho", alpha_2_code: "ID", country_id: 243},
  {name: "Illinois", alpha_2_code: "IL", country_id: 243},
  {name: "Indiana", alpha_2_code: "IN", country_id: 243},
  {name: "Iowa", alpha_2_code: "IA", country_id: 243},
  {name: "Kansas", alpha_2_code: "KS", country_id: 243},
  {name: "Kentucky", alpha_2_code: "KY", country_id: 243},
  {name: "Louisiana", alpha_2_code: "LA", country_id: 243},
  {name: "Alagoas", alpha_2_code: "AL", country_id: 39},
  {name: "Amapá", alpha_2_code: "AP", country_id: 39},
  {name: "Amazonas", alpha_2_code: "AM", country_id: 39},
  {name: "Bahia", alpha_2_code: "BA", country_id: 39},
  {name: "Ceará", alpha_2_code: "CE", country_id: 39},
  {name: "Distrito Federal", alpha_2_code: "DF", country_id: 39},
  {name: "Espírito Santo", alpha_2_code: "ES", country_id: 39},
  {name: "Goiás", alpha_2_code: "GO", country_id: 39},
  {name: "Maranhão", alpha_2_code: "MA", country_id: 39},
  {name: "Mato Grosso", alpha_2_code: "MT", country_id: 39},
  {name: "Mato Grosso do Sul", alpha_2_code: "MS", country_id: 39},
  {name: "Minas Gerais", alpha_2_code: "MG", country_id: 39},
  {name: "Pará", alpha_2_code: "PA", country_id: 39},
  {name: "Paraíba", alpha_2_code: "PB", country_id: 39},
  {name: "Paraná", alpha_2_code: "PR", country_id: 39},
  {name: "Pernambuco", alpha_2_code: "PE", country_id: 39},
  {name: "Piauí", alpha_2_code: "PI", country_id: 39},
  {name: "Rio de Janeiro", alpha_2_code: "RJ", country_id: 39},
  {name: "Rio Grande do Norte", alpha_2_code: "RN", country_id: 39},
  {name: "Rio Grande do Sul", alpha_2_code: "RS", country_id: 39},
  {name: "Rondônia", alpha_2_code: "RO", country_id: 39},
  {name: "Roraima", alpha_2_code: "RR", country_id: 39},
  {name: "Santa Catarina", alpha_2_code: "SC", country_id: 39},
  {name: "São Paulo", alpha_2_code: "SP", country_id: 39},
  {name: "Sergipe", alpha_2_code: "SE", country_id: 39},
  {name: "Tocantins", alpha_2_code: "TO", country_id: 39},
  {name: " Aguascalientes", alpha_2_code: "AGS.", country_id: 151},
  {name: " Baja California", alpha_2_code: "B.C.", country_id: 151},
  {name: " Baja California Sur", alpha_2_code: "B.C.S.", country_id: 151},
  {name: " Campeche", alpha_2_code: "CAMP.", country_id: 151},
  {name: " Chiapas", alpha_2_code: "CHIS.", country_id: 151},
  {name: " Chihuahua", alpha_2_code: "CHIH.", country_id: 151},
  {name: " Coahuila", alpha_2_code: "COAH.", country_id: 151},
  {name: " Colima", alpha_2_code: "COL.", country_id: 151},
  {name: "Maine", alpha_2_code: "ME", country_id: 243},
  {name: " Mexico City", alpha_2_code: "CDMX", country_id: 151},
  {name: " Durango", alpha_2_code: "DGO.", country_id: 151},
  {name: " Guanajuato", alpha_2_code: "GTO.", country_id: 151},
  {name: " Guerrero", alpha_2_code: "GRO.", country_id: 151},
  {name: " Hidalgo", alpha_2_code: "HGO.", country_id: 151},
  {name: " Jalisco", alpha_2_code: "JAL.", country_id: 151},
  {name: " México", alpha_2_code: "MÉX.", country_id: 151},
  {name: " Michoacán", alpha_2_code: "MICH.", country_id: 151},
  {name: " Morelos", alpha_2_code: "MOR.", country_id: 151},
  {name: " Nayarit", alpha_2_code: "NAY.", country_id: 151},
  {name: " Nuevo León", alpha_2_code: "N.L.", country_id: 151},
  {name: " Oaxaca", alpha_2_code: "OAX.", country_id: 151},
  {name: " Puebla", alpha_2_code: "PUE.", country_id: 151},
  {name: " Querétaro", alpha_2_code: "QRO.", country_id: 151},
  {name: " Quintana Roo", alpha_2_code: "QR", country_id: 151},
  {name: " San Luis Potosí", alpha_2_code: "SLP", country_id: 151},
  {name: " Sinaloa", alpha_2_code: "SIN.", country_id: 151},
  {name: " Sonora", alpha_2_code: "SON.", country_id: 151},
  {name: " Tabasco", alpha_2_code: "TAB.", country_id: 151},
  {name: " Tamaulipas", alpha_2_code: "TAMPS.", country_id: 151},
  {name: " Tlaxcala", alpha_2_code: "TLAX.", country_id: 151},
  {name: " Veracruz", alpha_2_code: "VER.", country_id: 151},
  {name: " Yucatán", alpha_2_code: "YUC.", country_id: 151},
  {name: " Zacatecas", alpha_2_code: "ZAC.", country_id: 151},
  {name: "Alberta", alpha_2_code: "AB", country_id: 48},
  {name: "British Columbia", alpha_2_code: "BC", country_id: 48},
  {name: "Manitoba", alpha_2_code: "MB", country_id: 48},
  {name: "New Brunswick", alpha_2_code: "NB", country_id: 48},
  {name: "Newfoundland and Labrador", alpha_2_code: "NL", country_id: 48},
  {name: "Nova Scotia", alpha_2_code: "NS", country_id: 48},
  {name: "Northwest Territories", alpha_2_code: "NT", country_id: 48},
  {name: "Nunavut", alpha_2_code: "NU", country_id: 48},
  {name: "Ontario", alpha_2_code: "ON", country_id: 48},
  {name: "Prince Edward Island", alpha_2_code: "PE", country_id: 48},
  {name: "Quebec", alpha_2_code: "QC", country_id: 48},
  {name: "Saskatchewan", alpha_2_code: "SK", country_id: 48},
  {name: "Yukon", alpha_2_code: "YT", country_id: 48}
])
SupplyFoodConfiguration.create!([
  {name: "Food Handling", description: "the importance of the food handling and health issues", value: nil, html_configuration: "Food Handling is important"},
  {name: "The value of a donation", description: "text to describe the value of a donation", value: nil, html_configuration: "Each donation is a proof of good will whose give some so important as food to a fellow men"},
  {name: "News", description: "news about funding and the media exposure", value: nil, html_configuration: "last news"},
  {name: "Services", description: "describe the services provided by your hunger relief project", value: nil, html_configuration: "we divide our work in 4 major activites : collect, storage, inspect and deliver"},
  {name: "Legal", description: "legal concerns and the legal agreement", value: nil, html_configuration: "<p>legal concerns</p><p>legal agreement</p>"},
  {name: "Volunteer form contract", description: "the term of contract of the volunteer service", value: nil, html_configuration: "<p> volunteer contract<p><p>as a volunteer i hereby accept that my work is volunteer, not paid</p>"},
  {name: "Volunteer intro page", description: "initial page from volunteer menu, explaining the importance and work of the volunteer", value: nil, html_configuration: "<p>the volunteer work is the base of any hunger relief program<p><p> since the material resources are scarce , the sucess of the project is based on the strict organization and planning and besides all, the good will of the volunteers.</p>"},
  {name: "State", description: "RJ", value: nil, html_configuration: ""},
  {name: "Country", description: "BR", value: nil, html_configuration: ""},
  {name: "City", description: "Rio de Janeiro", value: nil, html_configuration: ""},
  {name: "Volunteer letter of recommedation", description: "the model of letter of recomendation to volunteers", value: nil, html_configuration: "<p> the volunteer was of great importance to this initiative </p>"},
  {name: "Supplier letter of recommedation", description: "the model of letter of recomendation to suppliers", value: nil, html_configuration: "<p> the services of the supplier was very important to our initiative </p>"}
])
UserType.create!([
  {name: "Donor"},
  {name: "Volunteer"},
  {name: "Manager"},
  {name: "Supplier"},
  {name: "Consumer"}
])
