State.create!([
	{name: "Alagoas", alpha_2_code: "AL", country_id: 39},
	{name: "Amapá", alpha_2_code: "AP", country_id: 39},
	{name: "Amazonas", alpha_2_code: "AM", country_id: 39},
	{name: "Bahia", alpha_2_code: "BA", country_id: 39},
	{name: "Ceará", alpha_2_code: "CE", country_id: 39},
	{name: "Distrito Federal", alpha_2_code: "DF", country_id: 39},
	{name: "Espírito Santo", alpha_2_code: "ES", country_id: 39},
	{name: "Goiás", alpha_2_code: "GO", country_id: 39},
	{name: "Maranhão", alpha_2_code: "MA", country_id: 39},
	{name: "Mato Grosso", alpha_2_code: "MT", country_id: 39},
	{name: "Mato Grosso do Sul", alpha_2_code: "MS", country_id: 39},
	{name: "Minas Gerais", alpha_2_code: "MG", country_id: 39},
	{name: "Pará", alpha_2_code: "PA", country_id: 39},
	{name: "Paraíba", alpha_2_code: "PB", country_id: 39},
	{name: "Paraná", alpha_2_code: "PR", country_id: 39},
	{name: "Pernambuco", alpha_2_code: "PE", country_id: 39},
	{name: "Piauí", alpha_2_code: "PI", country_id: 39},
	{name: "Rio de Janeiro", alpha_2_code: "RJ", country_id: 39},
	{name: "Rio Grande do Norte", alpha_2_code: "RN", country_id: 39},
	{name: "Rio Grande do Sul", alpha_2_code: "RS", country_id: 39},
	{name: "Rondônia", alpha_2_code: "RO", country_id: 39},
	{name: "Roraima", alpha_2_code: "RR", country_id: 39},
	{name: "Santa Catarina", alpha_2_code: "SC", country_id: 39},
	{name: "São Paulo", alpha_2_code: "SP", country_id: 39},
	{name: "Sergipe", alpha_2_code: "SE", country_id: 39},
	{name: "Tocantins", alpha_2_code: "TO", country_id: 39},
	{name: " Alabama", alpha_2_code: "AL", country_id: 243},
	{name: " Alaska", alpha_2_code: "AK", country_id: 243},
	{name: " Arizona", alpha_2_code: "AZ", country_id: 243},
	{name: " Arkansas", alpha_2_code: "AR", country_id: 243},
	{name: " California", alpha_2_code: "CA", country_id: 243},
	{name: " Colorado", alpha_2_code: "CO", country_id: 243},
	{name: " Connecticut", alpha_2_code: "CT", country_id: 243},
	{name: " Delaware", alpha_2_code: "DE", country_id: 243},
	{name: " Florida", alpha_2_code: "FL", country_id: 243},
	{name: " Georgia", alpha_2_code: "GA", country_id: 243},
	{name: " Hawaii", alpha_2_code: "HI", country_id: 243},
	{name: " Idaho", alpha_2_code: "ID", country_id: 243},
	{name: " Illinois", alpha_2_code: "IL", country_id: 243},
	{name: " Indiana", alpha_2_code: "IN", country_id: 243},
	{name: " Iowa", alpha_2_code: "IA", country_id: 243},
	{name: " Kansas", alpha_2_code: "KS", country_id: 243},
	{name: " Kentucky", alpha_2_code: "KY", country_id: 243},
	{name: " Louisiana", alpha_2_code: "LA", country_id: 243},
	{name: " Maine", alpha_2_code: "ME", country_id: 243},
	{name: " Maryland", alpha_2_code: "MD", country_id: 243},
	{name: " Massachusetts", alpha_2_code: "MA", country_id: 243},
	{name: " Michigan", alpha_2_code: "MI", country_id: 243},
	{name: " Minnesota", alpha_2_code: "MN", country_id: 243},
	{name: " Mississippi", alpha_2_code: "MS", country_id: 243},
	{name: " Missouri", alpha_2_code: "MO", country_id: 243},
	{name: " Montana", alpha_2_code: "MT", country_id: 243},
	{name: " Nebraska", alpha_2_code: "NE", country_id: 243},
	{name: " Nevada", alpha_2_code: "NV", country_id: 243},
	{name: " New Hampshire", alpha_2_code: "NH", country_id: 243},
	{name: " New Jersey", alpha_2_code: "NJ", country_id: 243},
	{name: " New Mexico", alpha_2_code: "NM", country_id: 243},
	{name: " New York", alpha_2_code: "NY", country_id: 243},
	{name: " North Carolina", alpha_2_code: "NC", country_id: 243},
	{name: "  North Dakota", alpha_2_code: "ND", country_id: 243},
	{name: " Ohio", alpha_2_code: "OH", country_id: 243},
	{name: " Oklahoma", alpha_2_code: "OK", country_id: 243},
	{name: " Oregon", alpha_2_code: "OR", country_id: 243},
	{name: " Pennsylvania", alpha_2_code: "PA", country_id: 243},
	{name: " Rhode Island", alpha_2_code: "RI", country_id: 243},
	{name: " South Carolina", alpha_2_code: "SC", country_id: 243},
	{name: " South Dakota", alpha_2_code: "SD", country_id: 243},
	{name: " Tennessee", alpha_2_code: "TN", country_id: 243},
	{name: " Texas", alpha_2_code: "TX", country_id: 243},
	{name: " Utah", alpha_2_code: "UT", country_id: 243},
	{name: " Vermont", alpha_2_code: "VT", country_id: 243},
	{name: " Virginia", alpha_2_code: "VA", country_id: 243},
	{name: " Washington", alpha_2_code: "WA", country_id: 243},
	{name: " West Virginia", alpha_2_code: "WV", country_id: 243},
	{name: " Wisconsin", alpha_2_code: "WI", country_id: 243},
	{name: " Wyoming", alpha_2_code: "WY", country_id: 243},
	{name: " Aguascalientes", alpha_2_code: "Ags.", country_id: 151},
	{name: " Baja California", alpha_2_code: "B.C.", country_id: 151},
	{name: " Baja California Sur", alpha_2_code: "B.C.S.", country_id: 151},
	{name: " Campeche", alpha_2_code: "Camp.", country_id: 151},
	{name: " Chiapas", alpha_2_code: "Chis.", country_id: 151},
	{name: " Chihuahua", alpha_2_code: "Chih.", country_id: 151},
	{name: " Coahuila", alpha_2_code: "Coah.", country_id: 151},
	{name: " Colima", alpha_2_code: "Col.", country_id: 151},
	{name: " Mexico City", alpha_2_code: "CDMX", country_id: 151},
	{name: " Durango", alpha_2_code: "Dgo.", country_id: 151},
	{name: " Guanajuato", alpha_2_code: "Gto.", country_id: 151},
	{name: " Guerrero", alpha_2_code: "Gro.", country_id: 151},
	{name: " Hidalgo", alpha_2_code: "Hgo.", country_id: 151},
	{name: " Jalisco", alpha_2_code: "Jal.", country_id: 151},
	{name: " México", alpha_2_code: "Méx.", country_id: 151},
	{name: " Michoacán", alpha_2_code: "Mich.", country_id: 151},
	{name: " Morelos", alpha_2_code: "Mor.", country_id: 151},
	{name: " Nayarit", alpha_2_code: "Nay.", country_id: 151},
	{name: " Nuevo León", alpha_2_code: "N.L.", country_id: 151},
	{name: " Oaxaca", alpha_2_code: "Oax.", country_id: 151},
	{name: " Puebla", alpha_2_code: "Pue.", country_id: 151},
	{name: " Querétaro", alpha_2_code: "Qro.", country_id: 151},
	{name: " Quintana Roo", alpha_2_code: "QR", country_id: 151},
	{name: " San Luis Potosí", alpha_2_code: "SLP", country_id: 151},
	{name: " Sinaloa", alpha_2_code: "Sin.", country_id: 151},
	{name: " Sonora", alpha_2_code: "Son.", country_id: 151},
	{name: " Tabasco", alpha_2_code: "Tab.", country_id: 151},
	{name: " Tamaulipas", alpha_2_code: "Tamps.", country_id: 151},
	{name: " Tlaxcala", alpha_2_code: "Tlax.", country_id: 151},
	{name: " Veracruz", alpha_2_code: "Ver.", country_id: 151},
	{name: " Yucatán", alpha_2_code: "Yuc.", country_id: 151},
	{name: " Zacatecas", alpha_2_code: "Zac.", country_id: 151},
	{name: "Alberta", alpha_2_code: "AB", country_id: 48},
	{name: "British Columbia", alpha_2_code: "BC", country_id: 48},
	{name: "Manitoba", alpha_2_code: "MB", country_id: 48},
	{name: "New Brunswick", alpha_2_code: "NB", country_id: 48},
	{name: "Newfoundland and Labrador", alpha_2_code: "NL", country_id: 48},
	{name: "Nova Scotia", alpha_2_code: "NS", country_id: 48},
	{name: "Northwest Territories", alpha_2_code: "NT", country_id: 48},
	{name: "Nunavut", alpha_2_code: "NU", country_id: 48},
	{name: "Ontario", alpha_2_code: "ON", country_id: 48},
	{name: "Prince Edward Island", alpha_2_code: "PE", country_id: 48},
	{name: "Quebec", alpha_2_code: "QC", country_id: 48},
	{name: "Saskatchewan", alpha_2_code: "SK", country_id: 48},
	{name: "Yukon", alpha_2_code: "YT", country_id: 48}
])
